server:
  port: 17080
spring:
  application:
    name: issuemoaUserUsers
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#actuator config
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

api:
  endpoint:
    bookmarkFindByUserId: http://localhost:17070/support/bookmark/findByUserId
    recaptchaSiteVerify: https://www.google.com/recaptcha/api/siteverify
  secret:
    recaptcha: ENC(ykQJhpH7TtMuT4FeJjK+HlyFdHx/gQTO/tZvL4vLo+SRafL0OR2Dm+LJK0q9A1560qaM+flN2m8=)

jwt: # HS512 알고리즘 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ENC(VI4MfgzGP9i+LiWDRY0dYaJ/hXBDocUOR3LpuuFNaGK3BH2/b/tkCswVcRRed2wsj556Y8MAw+13b25s6Xeuvg2XbjOYRImlU30XbUD24MVy6xrSvqMYY+0Q4Uq/2MlT0J42h+G3MK/cYZW3uf73Aw==)