server:
  port: 37070
spring:
  application:
    name: issueMoaUsers
  config:
    import:
      - optional:configserver:http://gate.issuemoa.kr:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:38761/eureka
