server:
  port: 17070
spring:
  application:
    name: issueMoaUsers
  profiles:
    active: docker
  config:
    import:
      - common.yml
      - optional:configserver:http://192.168.0.31:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://issuemoa-eureka:8761/eureka
