server:
  port: 17070
spring:
  application:
    name: issueMoaUsers
  config:
    import:
      - optional:configserver:http://192.168.0.31:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.31:8761/eureka
