server:
  port: 17070
spring:
  application:
    name: issueMoaUsers
  config:
    import:
      - optional:configserver:http://61.102.114.235:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://61.102.114.235:8761/eureka
